# Data Science - Python Intro

## Installatie

Om Python en Jupyter Notebook te installeren volg je [deze link](https://www.anaconda.com/products/individual#windows).
Anaconda is een bundle met Python en een groot aantal extra packages die vaak gebruikt worden bij Data Science en Machine Learning.
Download de executable en installeer het.
Hierbij mogen de default opties gekozen worden.

Ook al heeft Anaconda zijn eigen package manager (conda), niet alle packages kunnen door deze correct gevonden worden. Daarom moet je ook nog pip installeren door middel van onderstaande commando.

Dit is bijgetypt als voorbeeld 

bla
bla bla

bla bla bla

**dit is in het vet**

* optie 1
* optie 2

In [1]:
!conda install pip

^C


Clone nu de github repo waar deze file in staat. Deze kan gevonden worden via [de link, pas dit aan naar de repo van dit jaar](TODO).
Open nu een commandprompt (cmd.exe) en navigeer met behulp van cd naar de folder waar je de repo geplaatst hebt.
Voer op die plaats het commando **jupyter notebook** uit.
Dit opent een webpagina met de inhoud van je folder waar je zat.
Open nu het notebook dat we hier gebruiken (Deze file noemt **03_PythonIntro**).

Op dit punt zou je hetzelfde moeten zien als hier staat.

## Jupyter notebook

Jupyter notebook maakt het mogelijk om hier zowel de opgave, uitleg als code te tonen en uit te voeren.
Hiervoor wordt er gebruik gemaakt van cellen.
Ook is het mogelijk om zowel code als tekstuele vragen te stellen.

Een korte intro over jupyter notebook kan je [hier](https://realpython.com/jupyter-notebook-introduction/) lezen.
In grote lijnen wordt er gewerkt met cellen. Het type van de cel bepaalt of het python-code of plain text (markdown) bevat.
Cellen worden automatisch toegevoegd na het uitvoeren van de laatste cel maar je kan ook er manueel toevoegen onder het menu-item insert of door gebruik te maken van de knoppen "a" en "b" (Hierbij moet je wel eerst uit de cell gaan door middel van Esc). Met deze laatste methode kan je op de gewenste plaats cellen gaan toevoegen.

Uitvoeren van een code cel zorgt ervoor dat de python code die in die cell staat uitgevoerd wordt. In het geval van een markdown cell wordt de tekst gerendered.
Om 1 cell uit te voeren is "shift+enter" de gemakkeljkste methode omdat dan de onderstaande cell automatisch geselecteerd wordt. Deze manier wordt ook gebruikt bij het pijltje met de tekst "Run" bovenaan.
Andere methoden kan je vinden onder het menu "Cell" waarbij je bijvoorbeeld ook van boven naar beneden alle cellen kan laten uitvoeren.
Als je ooit in een situatie zit waar je een endless loop gemaakt hebt of je code lijkt vast te zitten, kan je onder kernel een aantal manieren vinden om het uitvoeren te stoppen. 
Merk op dat als je de kernel stopt, je dan ook alle variabelen en objecten kwijt bent en je opnieuw de code vanin het begin moet uitvoeren.

**Let op:** Bij het pushen naar github van de code is het aangeraden om de output te verwijderen die je hebt gegenereerd.
Dit kan de bestandsgrootte sterk reduceren en vermijdt conflicten. 
Hierbij is het dan wel nodig om ervoor te zorgen dat je code van boven naar beneden kan uitgevoerd worden (met de knop run-all).

Met b maak je een nieuwe cell (standaard code cell)

maak deze markdown met m

a maakt een cell boven de huidige cell

een cell wegdoen doen, dan gebruik je x

indien je per ongeluk delete
* plak terug met v
* undo deletion met z

eventueel moet je ESC gebruiken om te stoppen met editen

shift+enter om een cell uit te voeren

## Python intro

Python is een open-source programmeertaal ontwikkeld en ontworpen begin jaren 90. 
Net zoals C# is het een object-georienteerde programmeertaal waarin gebruik gemaakt wordt van klassen en objecten voor structuur aan te brengen in je code. 
Het doel van Python is om een zeer leesbare programmeertaal te zijn en code lijkt sterk op pseudocode. 
In dit vak werken we met Python versie 3.x. 
De syntax vanaf versie 3 is licht afwijkend met die van Python versie 2.x.

Het grootste verschil met C# is dat Python een scripting taal is die gebruik maakt van een interpreter in plaats van een compiler. Dit houdt in dat er geen compile/build step is. Een file of een tekst met Python code wordt door de interpreter ingelezen en lijn voor lijn uitgevoerd.

Python code kan
 * Rechtstreeks in de commandline uitgevoerd worden. Voer hiervoor het commando "python" uit. Dit start de interpreter waar er berekeningen kunnen uitgevoerd worden.
 * Je kan een file aanmaken waar dezelfde lijnen in staan. Wanneer je nu navigeert naar je directory in commandline en daar het commando "python **filename**.py" uitvoert, dan krijg je hetzelfde resultaat. Merk op dat files met python code standaard de extensie .py hebben maar dat dit niet strikt noodzakelijk is.
 * Daarnaast kan je net hetzelfde doen in een cell van jupyter notebook

In [3]:
a = 5
b = 10
c = 20

d = a + b * c
print(d)

# dit is commentaar
# multiline bestaat typisch niet
'''
    dit is wat vals spelen
'''

d = a + b

205


De grootste verschillen met C# zijn:
* Een scripting taal dus geen compileer stap nodig (het kan wel gedaan worden voor de snelheid van het programma te verbeteren)
* Dynamisch typecasting dus moet niet steeds het type meegegeven worden bij het aanmaken van variabele, definieren van functies en klassen
* Indentation ipv van accolades voor code blocks

Nu ga ik een hele reeks zaken overlopen om de basis van python te leren kennen. 
Merk op dat in de loop van dit vak we python gaan gebruiken op een vereenvoudigde manier dus is het niet nodig om alle details te kennen van hoe python werkt.

In [40]:
# python is not strongly typed (types mogen wisselen en zijn maar belangrijk bij gebruik van de variabelen)
import enum


a = 5.2
a = "dit is een tekst"
a = int(7.3)

len("Hello world")

# list
lijst = [0, 1,2,3,4, "hello", "world"]
lijst[2]
lijst[-2]
lijst[3:5]
# min:max:step   -> wordt slicing genoemd , niets vermeld is ofwel begin voor min, einde voor max of 1 voor step
lijst[1::2]
lijst.insert(3, "a")
lijst.append("b")
lijst.extend([0, 1])
lijst = lijst + [0, 1]
print(lijst)

# dictionary
dictionary = {"key1": 5, "key2": 10}
dictionary["key1"] = 19
dictionary["key3"] = 20
print(dictionary)

# tuples
# deze getallen haren bij elkaar
tuplevoorbeeld = (5,10)
print(tuplevoorbeeld)
index0, index1 = tuplevoorbeeld
print(index0, index1)
# typisch gebruikt om meerdere waarden te returnen uit een functie

print(index0, index1, sep='\t')
print(f'test test {index0} test')

# input van command line
# input()

# iets verandere van type
#a = str(index0) #float
#'5' + (8)

if a > b:
    # bla bla bla
    pass
elif a == b:
    print("hier")
else:
    pass

for i in range(5):
    print(i)

for idx, i in enumerate(range(5)):
    print(idx, i*10)

while(b > 0):
    print(b)
    b -= 1   # geen -- en ++ maar -= en += wel

# def functie
def find_len(l):
    return len(l)

print(find_len(range(10)))

# classes
class Person:

    def __init__(self, name, age = 0, address = ''):
        self.age= age
        self.name = name
        self.address = address
        pass

persoon = Person("test1", 10)
persoon2 = Person("test2", 20)

print(persoon.age, persoon2.age)

# overerving
class Student(Person):

    def __init__(self, name, age=0, address=''):
        super().__init__(name, age, address)


[0, 1, 2, 'a', 3, 4, 'hello', 'world', 'b', 0, 1, 0, 1]
{'key1': 19, 'key2': 10, 'key3': 20}
(5, 10)
5 10
5	10
test test 5 test
0
1
2
3
4
0 0
1 10
2 20
3 30
4 40
10
10 20


### Oefening

* Maak een klasse Persoon aan, die minstens een naam en leeftijd en adres heeft.
* Maak een klasse Student aan die hiervan over erft die ook nog een dictionary bijhoudt met welke scores de student had voor welk vak. 
* Maak functies in deze klassen aan om scores toe te voegen, te tellen voor hoeveel vakken de student erdoor is en zijn gemiddelde te berekenen
* Maak een aparte functie aan die een lijst studenten als argument meekrijgt en bepaalt hoeveel studenten er door zijn.
* Maak een aparte functie aan die een lijst studenten als argument meekrijgt en bepaalt voor elk vak hoeveel studenten er door zijn.

In [2]:
# Oefening 1: Persoon

class Persoon:
    def __init__(self, naam, leeftijd, adres):
        # met de underscore geef je aan dat dit private is (wel nog zichtbaar maar je moet er afblijven)
        self._naam = naam
        self.naam = naam
        self.leeftijd = leeftijd
        self.adres = adres

p = Persoon("Jens", 31, "Zottegem")
print(p.naam, p.leeftijd, p.adres)


Jens 31 Zottegem


In [8]:
# Oefening 2: Student

class Student(Persoon):

    def __init__(self, naam, leeftijd, adres):
        super().__init__(naam, leeftijd, adres)
        self.scores = {}

    def add_score(self, vak, punt):
        self.scores[vak] = punt

    def aantal_vakken_geslaagd(self):
        aantal = 0

        for vak in self.scores:
            if self.scores[vak] > 9:
                aantal += 1

        return aantal

    def bereken_gemiddelde(self):
        
        aantal = len(self.scores)
        if aantal == 0:
            return 0

        som = 0

        for vak in self.scores:
            som += self.scores[vak]

        return som / aantal

s = Student("Jens", 31, "Zottegem")
print(s.naam, s.leeftijd, s.adres, s.scores)

s.add_score("Data Science", 18)
s.add_score("Big Data", 8)
s.add_score("Machine learning", 16)
print(s.naam, s.leeftijd, s.adres, s.scores)

print(s.aantal_vakken_geslaagd())
print(s.bereken_gemiddelde())

Jens 31 Zottegem {}
Jens 31 Zottegem {'Data Science': 18, 'Big Data': 8, 'Machine learning': 16}
2
14.0


In [9]:
# Oefening 4: Hoeveel studenten geslaagd voor een vak

def aantal_studenten_geslaagd(studenten, vak):
    aantal = 0

    for student in studenten:
        if vak in student.scores:
            if student.scores[vak] > 9:
                aantal += 1

    return aantal

s = Student("John Doe", 19, "Gent")
s.add_score("Data Science", 15)
s.add_score("Big Data", 12)
s.add_score("Machine Learning", 8)

studentenlijst = [s]

s = Student("Jane Doe", 20, "Leuven")
s.add_score("Data Science", 9)
s.add_score("Big Data", 5)
s.add_score("Machine Learning", 13)

studentenlijst.append(s)

s = Student("John Smith", 30, "Antwerpen")
s.add_score("Data Science", 19)
s.add_score("Big Data", 15)
s.add_score("Machine Learning", 0)

studentenlijst.append(s)

aantal_studenten_geslaagd(studentenlijst, "Data Science")

2

In [10]:
# Oefening 5: Hoeveel studenten geslaagd voor elk vak

def aantal_geslaagden_per_vak(studentenlijst):
    # gaan zoeken welke vakken er zijn
    vakken = {}
    for student in studentenlijst:
        for vak in student.scores:
            if vak not in vakken:
                vakken[vak] = 0

    # per vak het aantal geslaagden gaan zoeken
    for vak in vakken:
        vakken[vak] = aantal_studenten_geslaagd(studentenlijst, vak)

    return vakken

aantal_geslaagden_per_vak(studentenlijst)

{'Data Science': 2, 'Big Data': 2, 'Machine Learning': 1}

## Numpy Intro

De numpy libary of package is de kern van veel andere wiskundige rekentools for datamanagement of machine learning in python.
Het biedt onder andere een hoge performantie om te werken met rijen van meerdere dimensies en een reeks tools voor bewerkingen te doen met en op deze rijen.
* Een 1-dimensionale rij is een een normale rij
* Een 2-dimensionale rij is een matrix
* Een 3-dimensionale rij is bijvoorbeeld een RGB-figuur (derde dimensie bestaat uit drie elementen)

De standaard manier om deze package te gebruiken is door bovenaan je file de package te importeren met het commando:

In [12]:
import numpy as np

In [45]:
# aanmaken van arrays
np.array([0, 1, 2, 3, 4])
np.array([[0, 1], [2, 3], [4, 6]])
np.ones((5,10))
np.zeros((10,5))
np.eye(5)   # identiteitsmatrix

m = np.arange(10).reshape((5,2))
print(m)
m[1::2]

# berekeningen met matrices
m+m
m*m     # geen matrix vermenigvuldiging -> element per element vermenigvuldigen (elementwise)
m**3

m[m > 5]

np.sum(m, axis=0)
print(np.max(m))
print(np.amax(m))
np.mean(m)  # gemiddelde
np.median(m)

m2 = m.copy()   # zonder copy zet je enkel de referenties gelijk (dus dan worden beide aangepast) met een copy kopieer je de volledige numpy array
print(m)
m2[0,0] = -1
print(m, m2)

rnd = np.random.randint(-100, 100, (10, 5))
np.sort(rnd, axis=1)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
9
9
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] [[-1  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]]


array([[-89, -37,  21,  66,  79],
       [-55, -23,  21,  50,  89],
       [-45,  17,  29,  73,  76],
       [-91, -63, -62,  20,  55],
       [-89, -84, -60, -33,  85],
       [-63, -58,  -7,  15,  69],
       [-90,   5,  20,  73,  95],
       [-77, -52, -38,   5,  52],
       [-38, -36, -26,  36,  94],
       [-98, -85, -20,  39,  80]])

Maak nu de volgende oefeningen voor Numpy
* Maak 2 vierkante matrices met random waarden tussen 0 en 10. De ene is een 10x5 matrix, de andere is 5x10.
* Schrijf een functie die controleert of de dimensies van de matrices voldoen aan de voorwaarden voor matrix vermenigvuldiging
* Bereken de vermenigvuldiging van de matrix
* Toon de resultaten op alle even rijen
* Bereken de som van elke kolom
* Bereken het gemiddelde van de matrix
* Verander het type van de matrix naar een integer-type
* Toon alle rijen waar de 4e kolom een even getal bevat
* Wijzig de vorm van de matrix van een 10x10 naar een 5x20
* Bereken de getransponeerde matrix
* Bereken de vierkantswortel van elk element in deze matrix

In [54]:
m1 = np.random.random((10, 5))*10
m2 = np.random.random((5,10))*10

np.matmul(m2, m1)

array([[365.99182533, 317.91526637, 240.91726472, 322.64577764,
        378.12397423],
       [314.04421302, 298.10899744, 235.50417241, 261.35289849,
        351.52984875],
       [298.20782906, 259.53703978, 166.75387732, 213.47522498,
        298.60648136],
       [240.86412879, 222.65463402, 170.09524701, 225.2200851 ,
        250.09760537],
       [288.89575107, 246.28301141, 192.64850798, 261.17114286,
        344.3518466 ]])

## Pandas Intro

Pandas is een open-source software library die is geschreven voor Python om aan data manipulatie en analyse te doen. 
Het biedt met name datastructuren aan voor het bewerken en manipuleren van numerieke tabellen en tijdreeksen. 
Pandas is uitermate geschikt voor tabulaire data uit bijvoorbeeld relationele databases of spreadsheets.
De API die aangeboden wordt door deze library kan je [hier](https://pandas.pydata.org/pandas-docs/stable/reference/index.html) vinden.

Deze library biedt mogelijkheden aan om een breed gamma van dataformaten in te lezen en weg te schrijven als dataframe, bijvoorbeeld: csv, xlsx, Json en SQL.
De basis van de libary is het concept van Series en Dataframes. 
Een Series is een soort lijst dat een aantal soorten data kan bevatten (numerieke waarden, datums, strings, ...). 
Een Dataframe aan de andere hand is een collectie van series met een gemeenschappelijke index.
Een series is dan gelijkaardig aan een kolom in een tabel en een dataframe de hele tabel.

Net zoals bij Numpy moet deze library geimporteerd worden voor we ermee kunnen werken.
Dit kan aan de hand van de volgende regel.

In [55]:
import pandas as pd
#!pip install pandas

Nu ga ik eerst een voorbeeld tonen van het verschil van een Series en een Dataframe.

In [66]:
auteurs = pd.Series(["GRR Martin", "Andy Weir", "Tolkien", "JK Rowling"])

books = pd.Series([6, 3, 10, 8])

df = pd.DataFrame({"Auteur":auteurs, "nBooks": books})
display(df) # display pirnt dataframes mooier dan een eenvoudige print

# kolom toevoegen
df["Geboortejaar"] = pd.Series([1900, 1970, 1910])
df

Auteur  nBooks
0  GRR Martin       6
1   Andy Weir       3
2     Tolkien      10
3  JK Rowling       8

Auteur  nBooks  Geboortejaar
0  GRR Martin       6        1900.0
1   Andy Weir       3        1970.0
2     Tolkien      10        1910.0
3  JK Rowling       8           NaN

Merk op dat in deze laatste toevoeging een geboortejaar ontbrak. Dit is echter geen probleem want ontbrekende data wordt default op Nan gezet. 
Deze Nan waarden zien iets waar we later bij data cleaning veel aandacht aan gaan besteden.

In [79]:
# indexering van dataframes

df["Auteur"]
df.Auteur
# loc kan je gebruiken om te indexering op basis van de index/kolomnaam (waarde van de index)
df.loc[2]
df.loc[1:3]
df.loc[1, "Auteur"]
# iloc kan je gebruiken om te indexeren op basis van rangnummers (rijnummer)
df.set_index("Auteur")
df # index is niet aangepast
df2 = df.set_index("Auteur")
df.set_index("Auteur", inplace=True) # kan je maar 1 keer doen want anders bestaat die kolom niet meer
df

KeyError: 'Auteur'

Voor de verdere bewerkingen maken we een random dataframe aan met 1000 rijen en 5 kolommen.

In [106]:
# random df
df = pd.DataFrame(np.random.random((1000, 5)))
df.columns = ["A", "B", "C", "D", "E"]
df.describe()

# dimensions
len(df) # aantal rijen
len(df.columns) # aantal kolommen
df.shape

# indexing
df[(df.A > 0.8).__and__(df.B < 0.2)]

# drop columns, duplicates
df2.isna().sum(axis=1)
df2.dropna()
df2.dropna(axis=1, how='all')

#Reshaping data

#Handling null values

nBooks  Geboortejaar
Auteur                          
GRR Martin       6        1900.0
Andy Weir        3        1970.0
Tolkien         10        1910.0
JK Rowling       8           NaN

Nu kan je het zelf oefenen met de volgende oefeningen:
* Maak een Series aan met 500 willekeurige continue getallen tussen 0 en 20
* Maak een Series aan met 500 willekeurige integer getallen tussen 40 en 200 (let erop dat het dtype van deze kolom correct is)
* Maak een Dataframe aan op basis van deze twee Series. De eerste is de "Lengte" en de tweede de "Breedte".
* Bereken nu de oppervlakte van elke rij en sla dit op in een nieuwe kolom
* Bereken de gemiddelde en mediaan van deze nieuwe kolom
* Voor de oppervlakte willen we niet met komma-getallen werken. Verander het type van deze kolom dus naar int
* Toon de breedte van alle rijen waarvoor de oppervlakte groter is dan het gemiddelde.
* Toon enkel de rijen waarvoor de breedte groter is dan de lengte

In [116]:
import pandas as pd
a = pd.Series(['Quinten', 'Quinten', 'Quinten', 'Rob', 'Rob', 'Rob', 'Lorenzo', 'Lorenzo', 'Lorenzo'])
b = pd.Series(["Wiskunde", "Nederlands", "Duits", "Wiskunde", "Nederlands", "Duits", "Wiskunde", "Nederlands", "Duits"])
c = pd.Series([14,8,18,6,12,14,16,4,12])

x = pd.DataFrame({
    "Naam":a,   
    "Vak":b,
    "Score":c,
    "Percentage":(c/20)*100
})

display(x)

g = x.groupby(['Naam'])['Percentage'].idxmax()
display(g)
x.loc[g]


Naam         Vak  Score  Percentage
0  Quinten    Wiskunde     14        70.0
1  Quinten  Nederlands      8        40.0
2  Quinten       Duits     18        90.0
3      Rob    Wiskunde      6        30.0
4      Rob  Nederlands     12        60.0
5      Rob       Duits     14        70.0
6  Lorenzo    Wiskunde     16        80.0
7  Lorenzo  Nederlands      4        20.0
8  Lorenzo       Duits     12        60.0

Naam
Lorenzo    6
Quinten    2
Rob        5
Name: Percentage, dtype: int64

Naam       Vak  Score  Percentage
6  Lorenzo  Wiskunde     16        80.0
2  Quinten     Duits     18        90.0
5      Rob     Duits     14        70.0